# labels.yml

labels:
  - name: module:users
    color: 00CC33
    description:

  - name: module:organizations
    color: 0099FF
    description:

  - name: module:projects
    color: FF6666
    description:

  - name: module:tasks
    color: FF3300
    description:

  - name: config:workflows
    color: 0033FF
    description:

repos:
  - name: NhanHoVan/nestjs-example
    labels:
      - module:users
      - module:organizations
      - module:projects
      - module:tasks
      - config:workflows

# Add more labels as needed